// Talk data for the slide viewer (slides.html).
//
// To add a talk: export the deck to JPEGs + presenter notes with
// talks/import-keynote.sh, then append an object to this array.
// See talks/README.md for the full procedure.
//
// Fields:
//   id      URL slug — slides.html?talk=<id>
//   title   deck title
//   event   what the talk was (shown above the title)
//   context where/for whom (optional)
//   date    human-readable date (optional)
//   dir     folder holding the slide images, no trailing slash
//   ext     image extension
//   pad     zero-padding width of the image filenames (01.jpg -> 2)
//   slides  [{ n: <slide number>, notes: "<presenter notes>" }]

window.TALKS = [
    {
        id: "doctoral-defense-2026",
        title: "Uncovering the Limits of Machine Learning for Software Security",
        event: "Doctoral Defense",
        context: "Max Planck Institute for Security and Privacy, Bochum",
        date: "August 2026",
        dir: "talks/doctoral-defense-2026/slides",
        ext: "jpg",
        pad: 2,
        slides: [
            { n: 1, notes: "Welcome to my Doctoral Defense. Thank you all for coming here." },
            { n: 2, notes: "I want to start by showing this tweet from Marcel Böhme from Mai 2022. Its says „Interested in investigating the limits of machine learning for automated vulnerability discovery? Konrad Rieck, Kevin Borgolte and I have a number of PhD positions to be filled soon. Get in Touch!“. And jeah I was interested and I got in touch, and this was the starting point for my mission into exploring the limits of machine learning for software security." },
            { n: 3, notes: "And just to give you a quick overview. My PhD started in November 2022, and I worked on many projects during these four year until today, four of them which were successful and made it into my thesis. The first one was published at USENIX 2024, the second one at ISSTA 2025, the third one at NDSS 2026 and the fourth one will appear at ASE 2026 in October." },
            { n: 4, notes: "So, these are the four papers and I will now tell you about the most important findings that we presented in each of them." },
            { n: 5, notes: "Let’s start with the first paper, which has the title „Uncovering the Limits of Machine Learning for Automatic Vulnerability Detection“ and was joint work with my PhD advisor Marcel." },
            { n: 6, notes: "In 2023 when I mainly worked on this project, Machine Learning for Vulnerability Detection was on a sharp rise in popularity. Here you can see the number of papers on the topic published at the top Software Engineering and Security Conferences and Journals from 2020 to 2024. And you can see that the topic was growing rapidly in popularity around 2023 and 2024." },
            { n: 7, notes: "And we also analyzed how these papers define the problem of ML4VD and we found that 90% of the papers define vulnerability detection as a binary function-level classification problem." },
            { n: 8, notes: "But what does this actually mean. So take a look at this code sample. This is a function from the TensorFlow library, and the line marked in red was the cause of a security vulnerability. So basically, if the parameter num_splits is zero, this line can crash with a divide-by-zero error, leading to Denial of Service." },
            { n: 9, notes: "And how machine learning for vulnerability detection worked at the time, was to have a large number of these functions, each of of them with a binary label. The label is either this function has a security vulnerability or this function is secure. And these machine learning models were then evaluated on how accurate they are at classifying these function correctly. And as I’ve already told you, this was the way that 90% of the field was doing vulnerability detection." },
            { n: 10, notes: "And, the field was reporting quite good results. So on this is a leaderboard from 2023 for the Devign dataset. The Devign dataset was by far the most popular dataset at the time with more than 1k citations. And there were many papers reporting positive results on this dataset, for example the models on this leaderboard achieve around 70% accuracy. And since this dataset was perfectly balanced, meaning around 50% function were labeled as vulnerable and 50% as secure, this means the models were able to correctly predict the vulnerability label in 70% of the cases. Okay, and this was the situation when we were starting this project." },
            { n: 11, notes: "But does this mean that these models are actually capable of detecting security vulnerabilities? So we took a critical perspective because due to our background we were doubting that models were actually capable of detecting security vulnerabilities. So we were trying to come up with a methodology to test the models actual capability of understanding which semantic properties make a function vulnerable." },
            { n: 12, notes: "And the first methodology we proposed is asking the model to distinguish between functions labeled as vulnerable and their patched versions. In order to do this we collected a dataset of 13k C functions labeled as vulnerable and their patched versions, and we tested the top models from the Devign leaderboard, whether they can distinguish between them. And here you can see the results. So at the bottom we have the expected performance of a coinflip, which is 50% accuracy. And as you can see, these models barely overperform the coinflip, and some even underperform it. So the answer is: No, the models can’t distinguish functions labeled as vulnerable from their patches." },
            { n: 13, notes: "But why is this the case? How can we explain this failure? Why did the models still achieve high scores on the original Devign dataset?" },
            { n: 14, notes: "So to find this out, we used a tool called semantics-preserving transformations. These are transformations of the code that preserve their semantics. So for example, changing variable names consistently like in this example." },
            { n: 15, notes: "And we carried out a number of experiments where we apply the semantics-preserving transformations to either the functions used for testing the model, or the function used for training the model, or both, to find out whether the models rely on these semantically unrelated features when classifying these functions." },
            { n: 16, notes: "And the results are quite straightforward: If we apply a semantics-preserving transformation to the testing data that is not also applied to the training data, the accuracy drops. Which means, the high scores were previously achieved by relying on semantically unrelated features of the code." },
            { n: 17, notes: "So as a conclusion from this first project, we can say One, high scores on function-level datasets do not mean that the models actually understand the vulnerability-related semantic properties of the code. And this was evidenced by the models being unable to distinguish function labeled as vulnerable from their patches. Two, the high scores can be explained by relying on semantically unrelated features instead. And of course, this work puts a big question mark on the validity of the function-level paradigm in general, which we used as motivation to dive even deeper into these datasets." },
            { n: 18, notes: "Which brings me to the second project of my PhD. So this paper which is called „Top Score on the Wrong Exam: On Benchmarking in Machine Learning for Vulnerability Detection“ and won a ACM SIGSOFT Distinguished Paper Award at ISSTA 2025. This was joint work with my colleagues Jing and Marcel." },
            { n: 19, notes: "So while we did the first project, we actually spent a lot of time looking at the actual data that was used to test these models. So here again we have one of these functions, which I’ve already shown you in the beginning of the talk, which was the cause of a vulnerability in the TensorFlow project. And while looking at this function, we can ask the question: Can we even decide whether this function makes TensorFlow vulnerable by just looking at the function without its context?" },
            { n: 20, notes: "Because, in order for the line marked in red to crash, the parameter num_splits has to be zero. And as we can see here, num_splits is an argument to the function. So how can we be sure that it can ever be zero without looking at the context? The answer is of course „No, we can’t“. The vulnerability of this function depends on the context. It could both be the source of a vulnerability, or not, depending on what the context is." },
            { n: 21, notes: "And, as I’ve already told you for the first paper, 90% of papers published at the Top Software Engineering and Security conferences between 2020 and 2024 defined ML4VD exactly like this: As deciding whether a given function is vulnerable without considering the context." },
            { n: 22, notes: "So naturally, we asked the question: Is this approach, which is the de-facto standard approach to evaluate ML4VD, even valid?" },
            { n: 23, notes: "For this single function that I’ve shown you, it definitely is not valid. You simply can’t make the decision without the context." },
            { n: 24, notes: "So we asked, given a function that makes a program vulnerable, how often can we decide the vulnerability based on the functions code alone?" },
            { n: 25, notes: "And in order to find this out, we carried out an empirical study where we looked at 100 functions labeled as vulnerable from the top-3 most popular datasets, and two researcher, Jing and I, looked at each function and its context individually. For each function, we first had to decide, whether it actually introduces a vulnerability to its program, and if yes, whether the vulnerability depends on the context, or not." },
            { n: 26, notes: "And the results were very surprising. First, only 39-65% of the functions that were labeled as vulnerable, were actually the causes of vulnerabilities in their respective programs. This was also found out by other researchers, and can be explained by how the data is collected. If you are interested in the details, please check out the thesis or the paper." },
            { n: 27, notes: "And then, and this is one of the main findings of our paper, to our great surprise, 100%, so all of the function that were actually making their program vulnerable, depended on external context. There was not a single function where we could decide its vulnerability by just looking at the functions code alone." },
            { n: 28, notes: "So, based on this result, we can say, that the vulnerability of a function can not be decided in isolation." },
            { n: 29, notes: "But what about the other way around? Can we decide that a function is secure without considering the context?" },
            { n: 30, notes: "So again, we took 30 functions labeled as secure from each of the three datasets, and tried to come up with a context for each of them, under which they become the cause of a vulnerability. And the result was: We were able to create a context under which the function becomes the cause of a vulnerability for 90% of these functions." },
            { n: 31, notes: "And this means, together with our first finding, that the de-facto standard way of defining ML4VD as a function-level classification problem without context is fundamentally flawed." },
            { n: 32, notes: "But why do we still see high scores on these popular benchmark dataset if the underlying problem formulation is invalid?" },
            { n: 33, notes: "The answer was basically already given by our first paper. We added another experiment to this paper, showing that high scores can be achieved by relying on spurious features, meaning features that are spuriously correlated with the label but not in a causal relationship with it, like variable names for example." },
            { n: 34, notes: "So to conclude from this second project: Function-level classification without context was the standard way to approach ML4VD This standard way is fundamentally invalid, and Top scores can be explained by spurious features instead. And this meant of course, that an entire line of work was basically invalid." },
            { n: 35, notes: "And now two years later, we can of course attempt to look back and see whether our two papers achieved any impact in the field. Did the field actually stop approaching ML4VD as a function-level binary classification problem?" },
            { n: 36, notes: "So, to analyze this, we continued our literature survey to the years of 2025 and 2026 up until May …" },
            { n: 37, notes: "… and we can actually see a reverse of the trend, which perfectly correlates with the release of our two papers, which were released in 2023 and 2024." },
            { n: 38, notes: "Additionally, we also can see that of these papers doing ML4VD, the proportion of papers defining ML4VD as a function level classification problem is also going down in favor of other problem definition, for example by only constraining the context to the file or repository. So we can say, that the change we were hoping to initiate with our papers is actually starting to happen. But of course, correlation does not equal causation. We can not be certain that this change was actually caused by our papers, we can only say that it perfectly coincides." },
            { n: 39, notes: "Okay, let’s move on to the third project of my PhD, which is this paper called „Chasing Shadows: Pitfalls in LLM Security Research“ which appeared at this years NDSS and is joint work with fourteen other researchers from seven different institutions across Europe." },
            { n: 40, notes: "In this paper, we were motivated by the validity problems in ML4VD, and we asked ourselves whether these are just contained problems or whether these are symptoms of a greater validity crisis across the LLM for Security research area." },
            { n: 41, notes: "So we looked into the literature again, this time into all papers on LLMs for Security and Security and Safety of LLMs published at the top Security and Software Engineering conferences between 2023 and 2024." },
            { n: 42, notes: "And we identified nine potential pitfalls, that span across the entire LLM lifecycle. A pitfall is just what we call a problem of a paper that can potentially undermine its research validity. I won’t explain all of the nine pitfalls in this presentation, but if you are interested you can check out our website at llmpitfalls.org or the paper, for example." },
            { n: 43, notes: "Just as a quick example, one of the pitfalls we identified is the model ambiguity pitfall. Model Ambiguity means that the paper provides insufficient details to precisely identify the model that was used, including essential configuration like the quantization level of the model weights. For example, when a paper states that it used GPT-4o for an experiment, this could resolve to multiple versions of GPT-4o that might show different behavior. Omitting such information, can make potentially make reproducibility harder, or even impossible." },
            { n: 44, notes: "After identifying the pitfalls, we of course wanted to find out how prevalent they actually are in the literature." },
            { n: 45, notes: "So again, we carried out a huge literature review with our team of fifteen researchers and labeled each paper for each of the pitfalls. Here you can see an aggregation of these results. To our surprise, pitfalls were very prevalent across these paper. EVERY paper was affected by AT LEAST one pitfall, and some of the pitfalls, like model ambiguity were extremely prevalent, with 86% of papers being affected by this pitfall." },
            { n: 46, notes: "And we also reviewed how many of these pitfalls were discussed or acknowledged in the papers, if they were affected. And we found that only 15% were discussed, which means that the awareness about these pitfalls is very low." },
            { n: 47, notes: "And we were also interested how impactful these pitfalls can be. Let’s say a paper is affected by a pitfall, how bad are the consequences? Can these pitfalls actually undermine the research validity?" },
            { n: 48, notes: "To investigate this question, we implemented five case studies on the four most popular pitfalls. As an example, here are the results of our impact investigation for the model ambiguity pitfall. What you can see here is a robustness evaluation of a few open-source LLMs with different quantization levels. We tested the robustness of these models by attacking them with a suite of prompt-based attacks, and the attackers goal was to elicit a secret key from the model that the model was told to keep secret. And as you can see, the attack success rates of the same models under different quantization levels can vary drastically. For example, in the first row, the attack succeeded in 69% of the cases for 2-bit quantization, but only for 14% of cases for 8 bit quantization. So if the quantization level would not be mentioned in this case, the reproducibility would be seriously undermined." },
            { n: 49, notes: "And of course, we also wanted to do something to make the situation better, so we sprovide a list of guidelines and recommendations for each pitfalls, to provide advice on how each of these pitfalls should be avoided or handled. You can check out our website for a up-to-date list of best practices, if you are interested." },
            { n: 50, notes: "So from this third project, we can conclude that pitfalls are extremly prevalent and awareness is low. we can conclude that pitfalls can undermine research validity and reproducibility, and that there is still a way out by continuously developing and focusing on best practices" },
            { n: 51, notes: "This brings me to the fourth and final project of my PhD, which resulted in the paper „How and Why Agents can Identify Bug-Introducing Commits“, which again was joint work with Marcel." },
            { n: 52, notes: "For this project we have to go back to 2005, where three researchers abbreviated with SZZ asked the following question: When do change induce fixes in software repositories? To my great pleasure, we even have the second Z sitting in this room, because SZZ stands for Sliwerski, Zimmermann and Zeller, who just won the ACM SIGSOFT Impact Award for their paper from 2005. This paper inspired a ton of follow-up work on the task of identifying bug-introducing changes in software repositories." },
            { n: 53, notes: "Our work focuses on Bug-Introducing Commit Identification, which is one of the tasks the SZZ paper unlocked. Given a fix commit that repairs a bug in a software repository, identify the set of bug-introducing commits, where each bug-introducing commit introduced a change that contributed to or caused the bug that the fix commit resolves. This task is important for Software Security, because automating it allows to determine the versions affected by a security-relevant bug automatically." },
            { n: 54, notes: "So historical approaches, including the approach introduced by SZZ paper, mainly focused on heuristics. For example, they determined the bug-introducing commits by determining the commits that added or modified the lines last that were later removed by the fix commit. And over the last 20 years, there have been many extensions and adaptations to the original approach, including approaches using machine learning techniques such as LLMs." },
            { n: 55, notes: "We were interested in exploring whether agentic systems can overcome the limitations of the previous heuristics and pure ML-based approaches approaches, and if yes, to find out how they do it." },
            { n: 56, notes: "In order to investigate this, we created an agentic system called SZZ-Agent. SZZ-Agent iteratively splits an ordered set of candidate commits in the middle using binary search, and then asks for the software at the state of the middle commit: Is the bug already there. Doing so, it reduces the candidate set further and further, until the set is so small that the agent can directly select a commit." },
            { n: 57, notes: "This approach already works remarkably well, beating over 20 years of progress on the most popular Linux kernel dataset. And since it uses binary search, we thought it should already be pretty close to the limit of efficiency we could reach at this problem." },
            { n: 58, notes: "However, we also carried out a number of ablation studies, to see which components of SZZ-Agent contributed how much to its success." },
            { n: 59, notes: "During one of these ablation studies we actually made a surprising finding. We noticed that if we increase the number of commits that have to be left in order for the binary search to stop and the direct commit selection to start, the performance does not get worse, and the approach actually gets more efficient by spending less tokens." },
            { n: 60, notes: "So this surprising results of our ablation study lead us to develop a second, even simpler, agentic system called Simple-SZZ-Agent that directly select the bug-introducing commit from a candidate set of commits." },
            { n: 61, notes: "Doing so, it is much more efficient that our initial agentic system, while even outperforming it on the datasets that we tested." },
            { n: 62, notes: "But we didn’t stop there. Of course we wanted to find out HOW the agentic system is able to detect the bug-introducing commit among a large candidate set. These candidate sets sometimes grow to 10k or more commits, so the agentic system really has to find a way to efficiently navigate the set to find the culprit." },
            { n: 63, notes: "And the answer is simply search. The agent uses the unix tool grep to search the candidate set of commits for patterns that it derived from the fix commit diff and message to find the bug-introducing commit. Doing so, it only has to read a small number of commits, instead of analyzing multiple files at each stage of the binary search of our first agentic system." },
            { n: 64, notes: "And to conclude from our fourth and final project, One: Agentic systems can be very effective for software security tasks, and can potentially overcome or circumvent many problems of previous techniques, Two, Do ablation studies. I see many papers where the ablation studies just confirm that their system is the best, and I think there is great value on actually trying hard to find out what actually contributes to the results you are getting, as we have seen in this work, and Three The agents we investigated are good at search, which can be leveraged to improve efficiency." },
            { n: 65, notes: "So, this were the most important findings from the four paper that I worked on." },
            { n: 66, notes: "I also want to briefly talk about what’s next. What are future direction that we can derive from my doctoral work?" },
            { n: 67, notes: "So first, for ML4VD. Of course, function-level classification is invalid. So the field should abandon it. And as we have seen in our impact analysis, the field is actually starting to abandon it. However, I think we also gathered evidence that binary classification in general is not an optimal paradigm for vulnerability detection, because you never know if the model made the correct decision for the right reasons. Therefore I propose, and I proposed that already in the two papers on the topic, that the field should focus on alternative problem formulations such as bug-triggering test case generation and exploit generation instead. And actually, the field has already moved towards these two paradigms. There are two benchmarks in particular which I want to quickly mention, CyberGym and ExploitGym, which have partly been developed by colleagues at MPI-SP and which evaluate ML4VD in a much better way. Second, I think we still understand only very little about the fundamental and practical limits of agents for software security. I think today, it is no longer the question of whether agentic systems can detect vulnerabilities, they can, but where are there limits in terms of efficiency, what are fundamental trade-offs, and what are fundamental limits? Can we expect agentic systems of the future to „find all the bugs“, or are there fundamental limits or trade-offs which make that impossible or impractical? And I also think its interesting to focus on the generation side. Agents can basically generate entire software systems based on high-level natural language specifications, but how can we ensure that these systems adhere to security properties? And I am very happy to announce that I will try to explore these questions at Paderborn University starting in November, where I will work as a PostDoc with Professor Eric Bodden." },
            { n: 68, notes: "And then, of course, I would like to say thank you. Thank you to Marcel who has been an amazing PhD advisor to me, thank you to my resarch group here at MPI-SP for making the four years a great pleasure, thank you to all of my resarch collaborators, thank you to my wife, and last but not least thank you to the committee: Professor Michael Pradel, Professor Andreas Zeller, Professor Kevin Borgolte, Dr. Jana Hofmann, and Dr. Marcel Böhme, for reviewing my thesis and for coming here today to serve on my comittee." },
            { n: 69, notes: "And to you, the audience, thank you all all for coming today. I’ll leave you here with the conclusion slides from each of the four projects for the Q&A." }
        ],
    },
];
